# wrangler.toml
name = "lite-alpha"
compatibility_date = "2024-12-04"
main = "worker.js"

[env]
account_id = "b3562d79a9d4c362302e30e42e77a112"
workers_dev = true

[[kv_namespaces]]
binding = "Alpha"
id = "0aec69714b204ea4912a7d622473ee85"
preview_id = "0aec69714b204ea4912a7d622473ee85"

[vars]
TZ = "UTC"
