# wrangler.toml
name = "collider-beta-backend"
compatibility_date = "2024-12-04"

[env]
account_id = "892973ecf5177f94c0bc003d89f498b6"
workers_dev = true

[[kv_namespaces]]
binding = "Antitoken_Collider_Beta"
id = "e0fc61a0f9224afa8f01fd3f38b119f9"
preview_id = "e0fc61a0f9224afa8f01fd3f38b119f9"

[vars]
TZ = "UTC"
