# wrangler.toml
name = "collider-beta-backend"
compatibility_date = "2024-12-04"

[env]
account_id = "892973ecf5177f94c0bc003d89f498b6"
workers_dev = true

[[kv_namespaces]]
binding = "Antitoken_Collider_Beta"
id = "f8feb99c63a74cefab521689b0766a94"
preview_id = "f8feb99c63a74cefab521689b0766a94"
