# wrangler.toml
name = "collider-alpha-backend"
compatibility_date = "2024-12-04"

[env]
account_id = "892973ecf5177f94c0bc003d89f498b6"
workers_dev = true

[[kv_namespaces]]
binding = "Antitoken_Collider_Alpha"
id = "e23bff096fdb4533b40c622f926ba41c"
preview_id = "e23bff096fdb4533b40c622f926ba41c"
