# wrangler.toml
name = "collider-alpha-backend"
compatibility_date = "2024-12-04"

[env]
account_id = "892973ecf5177f94c0bc003d89f498b6"
workers_dev = true

[[kv_namespaces]]
binding = "Antitoken_Collider_Alpha"
id = "27907d49fc1b4af2b2a976900317f87e"
preview_id = "27907d49fc1b4af2b2a976900317f87e"

[vars]
TZ = "UTC"
